// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import "./globals.css";

// export const metadata = {
//   title: "Game Atlas",
//   description: "Discover top games and details",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-950 text-white">{children}</body>
//     </html>
//   );
// }

import "./globals.css";
import Header from "../components/ui/Header";
import Footer from "../components/ui/Footer";
import Hero from "@/components/layout/Hero";

export const metadata = {
  title: "Game Atlas",
  description: "Discover top games and details",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-linear-to-br from-gray-950 via-gray-900 to-gray-950 text-white">
        <Header />
        <Hero />

        <main className="grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
